#!/usr/bin/env node
/*
  build-css.js — concatenates the site's CSS into the ONE stylesheet that ships.

    assets/css/base.css                      (tokens + reset + shared components; always first)
    assets/css/sections/top.css              (always first among sections)
    assets/css/sections/<others>.css         (alphabetical)
  → assets/app.css                           (with a generated banner)

  index.html links only assets/app.css. Re-run after editing any source file:
    node marketing/tools/build-css.js
  Dependency-free. Exit 1 if base.css is missing or a section file cannot be read.
*/
"use strict";

const fs = require("fs");
const path = require("path");
const zlib = require("zlib");

// Generated app.css ships without source comments: the partials keep them, the
// bundle drops them so the byte budget reflects what visitors actually download.
function stripComments(css) {
  var out = '', i = 0;
  while (i < css.length) {
    var a = css.indexOf('/*', i);
    if (a === -1) { out += css.slice(i); break; }
    out += css.slice(i, a);
    var b = css.indexOf('*/', a + 2);
    if (b === -1) break;
    i = b + 2;
  }
  return out.replace(/[ \t]+$/gm, '').replace(/\n{3,}/g, '\n\n');
}


const SITE = path.resolve(__dirname, "..", "site");
const CSS_DIR = path.join(SITE, "assets", "css");
const BASE = path.join(CSS_DIR, "base.css");
const SECTIONS_DIR = path.join(CSS_DIR, "sections");
const OUT = path.join(SITE, "assets", "app.css");

function rel(p) { return path.relative(SITE, p).split(path.sep).join("/"); }

if (!fs.existsSync(BASE)) {
  console.error("build-css: missing " + rel(BASE));
  process.exit(1);
}

let sectionFiles = [];
if (fs.existsSync(SECTIONS_DIR)) {
  sectionFiles = fs
    .readdirSync(SECTIONS_DIR)
    .filter((f) => f.endsWith(".css") && !f.startsWith("."))
    .sort((a, b) => a.localeCompare(b, "en"));
  const i = sectionFiles.indexOf("top.css");
  if (i > 0) { sectionFiles.splice(i, 1); sectionFiles.unshift("top.css"); }
}

const sources = [BASE].concat(sectionFiles.map((f) => path.join(SECTIONS_DIR, f)));
const parts = [];
for (const file of sources) {
  let css;
  try { css = fs.readFileSync(file, "utf8"); }
  catch (e) { console.error("build-css: cannot read " + rel(file) + ": " + e.message); process.exit(1); }
  parts.push("/* ==== " + rel(file) + " ==== */\n" + stripComments(css).replace(/\s+$/, "") + "\n");
}

const banner =
  "/*! shifts-ai.store — assets/app.css — GENERATED by tools/build-css.js on " + new Date().toISOString() + "\n" +
  " *  DO NOT EDIT. Edit assets/css/base.css or assets/css/sections/<id>.css and rerun: node marketing/tools/build-css.js\n" +
  " *  Sources (in order): " + sources.map(rel).join(", ") + "\n" +
  " */\n\n";

const output = banner + parts.join("\n");
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, output, "utf8");

const raw = Buffer.byteLength(output, "utf8");
const gz = zlib.gzipSync(output).length;
console.log(
  "build-css: wrote " + rel(OUT) + " from " + sources.length + " file(s) — " +
  (raw / 1024).toFixed(1) + " KB raw, " + (gz / 1024).toFixed(1) + " KB gzipped"
);
