#!/usr/bin/env node
/* Self-hosted webfonts. Downloads the arabic + latin subsets of the two brand families from Google Fonts into
 * site/assets/fonts/ and writes site/assets/css/fonts.css (the @font-face rules pointing at those files) plus
 * src/fonts.json (the manifest build-pages.js uses to emit <link rel=preload>).
 *
 * Why self-host: the same bytes as Google Fonts, but on our own origin, so the browser finds them in the HTML
 * (preload) instead of after a third-party CSS round-trip — that is what was shifting the layout when the font
 * swapped in — and no visitor data goes to a third party.
 *
 * Run only when the font list changes: node marketing/tools/fetch-fonts.js
 * Normal builds just use the committed files. */
'use strict';
const fs = require('fs'), path = require('path'), https = require('https');
const M = path.join(__dirname, '..'), FONT_DIR = path.join(M, 'site/assets/fonts');
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36';
const CSS_URL = 'https://fonts.googleapis.com/css2?family=Alexandria:wght@600;700&family=IBM+Plex+Sans+Arabic:wght@400;500;600&display=swap';
const KEEP = new Set(['arabic', 'latin']);          // the only subsets this site needs
const SLUG = { 'Alexandria': 'alexandria', 'IBM Plex Sans Arabic': 'plexarabic' };

const get = (url, bin) => new Promise((res, rej) => https.get(url, { headers: { 'User-Agent': UA } }, r => {
  if (r.statusCode !== 200) return rej(new Error(url + ' → HTTP ' + r.statusCode));
  const chunks = []; r.on('data', c => chunks.push(c)); r.on('end', () => res(bin ? Buffer.concat(chunks) : Buffer.concat(chunks).toString('utf8')));
}).on('error', rej));

(async () => {
  fs.mkdirSync(FONT_DIR, { recursive: true });
  const css = await get(CSS_URL, false);
  const blocks = [...css.matchAll(/\/\* ([a-z-]+) \*\/\s*@font-face \{([^}]*)\}/g)];
  const faces = [];
  for (const [, subset, body] of blocks) {
    if (!KEEP.has(subset)) continue;
    const family = /font-family: '([^']+)'/.exec(body)[1];
    const weight = /font-weight: (\d+)/.exec(body)[1];
    const range = /unicode-range: ([^;]+);/.exec(body)[1].trim();
    const url = /url\((https:\/\/[^)]+)\)/.exec(body)[1];
    const file = `${SLUG[family]}-${weight}-${subset}.woff2`;
    const bytes = await get(url, true);
    fs.writeFileSync(path.join(FONT_DIR, file), bytes);
    faces.push({ family, weight, subset, file, range, bytes: bytes.length });
    console.log(`${family} ${weight} ${subset} — ${bytes.length} B → assets/fonts/${file}`);
  }
  fs.writeFileSync(path.join(M, 'src/fonts.json'), JSON.stringify(faces, null, 1) + '\n');
  const out = ['/* GENERATED by tools/fetch-fonts.js — self-hosted subsets of Alexandria + IBM Plex Sans Arabic.',
    ' * Edit the font list in that script, not here. */'];
  for (const f of faces) out.push(
    `@font-face{font-family:'${f.family}';font-style:normal;font-weight:${f.weight};font-display:swap;` +
    `src:url('/assets/fonts/${f.file}') format('woff2');unicode-range:${f.range};}`);
  fs.writeFileSync(path.join(M, 'site/assets/css/fonts.css'), out.join('\n') + '\n');
  const total = faces.reduce((a, f) => a + f.bytes, 0);
  console.log(`\n${faces.length} faces · ${(total / 1024).toFixed(0)} KB total · wrote assets/css/fonts.css and src/fonts.json`);
})().catch(e => { console.error(e.message); process.exit(1); });
