/**
 * Booking QR utilities — Phase 1.
 *
 * Centralizes generation of the secure scanner token (qr_token) and the
 * displayable QR PNG data URL that encodes it. Existing booking_code stays
 * as a human-readable fallback for manual entry.
 *
 * Do not refactor unrelated booking creation logic — only call
 * generateBookingQrPayload() at the moment a HourlyBooking is being created
 * and spread its result into the booking document.
 */

const { randomBytes } = require('crypto');
const QRCode = require('qrcode');

/**
 * Generate a cryptographically random 32-byte token (64 hex chars).
 * Used as the scanned-QR payload. Not guessable.
 */
const generateQrToken = () => randomBytes(32).toString('hex');

/**
 * Build a QR data URL (PNG) encoding the supplied payload.
 * Returns null on failure — caller decides whether to abort.
 */
const renderQrDataUrl = async (payload) => {
  try {
    return await QRCode.toDataURL(String(payload), { width: 300, margin: 2 });
  } catch (error) {
    console.error('QR_RENDER_FAILED', error?.message || error);
    return null;
  }
};

/**
 * Generate a fresh { qr_token, qr_code } pair where qr_code is a PNG data URL
 * encoding the qr_token. Use this at booking creation time.
 *
 * The booking_code remains the existing human-readable fallback and is
 * generated by the caller as before — we DO NOT change booking_code here.
 */
const generateBookingQrPayload = async () => {
  const qr_token = generateQrToken();
  const qr_code = await renderQrDataUrl(qr_token);
  return { qr_token, qr_code };
};

module.exports = {
  generateQrToken,
  renderQrDataUrl,
  generateBookingQrPayload
};
